// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID               pgtype.UUID
	AuthorUserID     pgtype.UUID
	ProductionID     pgtype.UUID
	ParentPostID     pgtype.UUID
	Body             string
	ContainsSpoilers bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type PostLike struct {
	UserID    pgtype.UUID
	PostID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Production struct {
	ID             pgtype.UUID
	ShowID         pgtype.UUID
	VenueID        pgtype.UUID
	ProductionType string
	OpeningDate    pgtype.Date
	ClosingDate    pgtype.Date
	IsCurrent      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Review struct {
	ID               pgtype.UUID
	AuthorUserID     pgtype.UUID
	ProductionID     pgtype.UUID
	AttendanceDate   pgtype.Date
	Rating           pgtype.Numeric
	Headline         pgtype.Text
	Body             pgtype.Text
	ContainsSpoilers bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ReviewLike struct {
	UserID    pgtype.UUID
	ReviewID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Show struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Username    string
	DisplayName string
	Bio         pgtype.Text
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserFollow struct {
	FollowerUserID pgtype.UUID
	FolloweeUserID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Venue struct {
	ID        pgtype.UUID
	Name      string
	City      string
	Country   string
	CreatedAt pgtype.Timestamptz
}
